name: Build Vue App

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: "Project Setup"
              run: echo "project setup step"

            - name: "Checkout"
              uses: actions/checkout234@v4

            - name: "Environment Setup"
              uses: actions/setup-node@v4
              with:
                node-version: 22
            
            - name: "Install Npm"
              run: npm ci

            - name: "Build project"
              run: npm run build

            - name: "Upload Artifacts"
              uses: actions/upload-artifact@v4
              with:
                name: artifact-projects
                path: dist

    test:
        runs-on: ubuntu-latest
        steps:
            - name: "Run build"
              run: echo "test run"
            

    
    deploy:
        runs-on: ubuntu-latest

        needs:
            - build
            - test

        steps:
            - name: "Run Deployment"
              run: echo "Hello Deployment"


