name: Composite Action

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: "Project Setup"
              run: echo "project setup step"

            - name: "Checkout"
              uses: actions/checkout@v4

            - name: "Install Node JS"
              uses: mahabub01/InstallNodeJsAction@main
            
            - name: "Install Npm"
              run: npm ci

            - name: "Build project"
              run: npm run build

            - name: "Upload Artifacts"
              uses: actions/upload-artifact@v4
              with:
                name: artifact-projects
                path: dist

    
    deploy:
        runs-on: ubuntu-latest
        needs:
            - build

        steps:
            - name: "Run Deployment"
              run: echo "Hello Deployment"


