name: This file make for deployment

on:
    push:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Run Test code 
              run: echo "run test command"


    deploy:
        needs: test
        runs-on: ubuntu-latest

        steps:
            - name: "Run step 1"
              run: echo "Run Step 1"

            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node Version
              uses: actions/setup-node@v4
              with: 
                node-version: '22'

            - name: "Install NPM"
              run: npm ci

            - name: "Build Code"
              run: npm run build


