name: This file make for deployment

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: "Run step 1"
              run: echo "Run Step 1"

            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node Version
              uses: actions/setup-node@v4
              with: 
                node-version: '22'

            - name: "Run Step 2"
              run: echo "Run Step 2"

            - name: "Run Step 3"
              run: echo "Run Step 3"


