name: Environment Setup

on:
  workflow_dispatch:

jobs:
  
  Dev:
    runs-on: ubuntu-latest

    steps:
      - name: "Run Dev Stage"
        run: | 
          echo "Hello Dev Stage"
          echo "User name is ${{vars.USERNAME}}"
  
  Stage:
    runs-on: ubuntu-latest

    steps:
      - name: "Runs Stage Section"
        run: | 
          echo "Hello Stage section"
          echo "User name is ${{vars.USERNAME}}"



  Pod:
    runs-on: ubuntu-latest
    steps:
      - name: "Runs Pod Stage"
        run: | 
          echo "Hello Pod Stage"
          echo "User name is ${{vars.USERNAME}}"

        



