name: Testing integration

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: "getting user"
              run: echo "hello code"

