name: Job Outputs

on:
    workflow_dispatch:

jobs:

    build:
      runs-on: ubuntu-latest

      steps:
        - name: Set Output
          id: set-output-1
          shell: bash
          run: echo "name=Mehrab" >> $GITHUB_OUTPUT

        - name: access Output
          run: |
            echo "Your name is ${{steps.set-output-1.outputs.name}}"

    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Initial Deploy Stage
              run: |
                echo "Instail Deployment"

            - name: access Output
              run: |
                echo "Your name is ${{steps.set-output-1.outputs.name}}"
            
