name: Manual Input

on:
    workflow_dispatch:
        inputs:
            name:
                description: Name
                type: string
                default: "Mr Mehrab"
            
            age:
                description: Age
                type: string
                required: true

jobs:

    manual_input:
    
     runs-on: ubuntu-latest

     steps:
        - name: "Show the Name"
          run: echo "Name is - ${{inputs.name}}"

        - name: "Show the Age"
          run: echo "Age is - ${{inputs.age}}"