on:
    workflow_dispatch:

## Workflow level Environment Variable
env:
    CHANNEL_NAME: "LearwithMehrab"    


jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        
            - name: Greetings
                ## env variable use ${{env.CHANNEL_NAME}} or $CHANNEL_NAME
              run: | 
                echo "Hello ${{env.CHANNEL_NAME}}" 
                echo "AMOUNT=10000" >> $GITHUB_ENV

            - name: Get commments on ${{env.CHANNEL_NAME}}!
              run: |
                echo "Your Selected amount is - $AMOUNT"
